/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.epn.VentanasProyectoFinal;

import ec.edu.epn.ClasesProyectoFinal.Compra;
import ec.edu.epn.ClasesProyectoFinal.Venta;
import java.util.ArrayList;

/**
 *
 * @author AnitaGabriela
 */
public class GUIEquiposInformaticos extends javax.swing.JFrame {

    PnlRegistrarCompra panelRegistrarCompra;
    PnlRegistrarVenta panelRegistrarVenta; 
    static ArrayList<Compra> compras;
    static ArrayList<Venta> ventas;
    /**
     * Creates new form GUIEquiposInformáticos
     */
    public GUIEquiposInformaticos() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        panelRegistrarCompra = new PnlRegistrarCompra();
        panelRegistrarVenta = new PnlRegistrarVenta();
        compras = new ArrayList<>();
        ventas = new ArrayList<>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnActividades = new javax.swing.JMenu();
        mnRegistrarCompra = new javax.swing.JMenuItem();
        mnRegistrarVenta = new javax.swing.JMenuItem();
        mnStock = new javax.swing.JMenu();
        mnVerificarStock = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INVENTARIO");

        mnActividades.setText("Actividades");

        mnRegistrarCompra.setText("Registrar Compra");
        mnRegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegistrarCompraActionPerformed(evt);
            }
        });
        mnActividades.add(mnRegistrarCompra);

        mnRegistrarVenta.setText("Registrar Venta");
        mnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegistrarVentaActionPerformed(evt);
            }
        });
        mnActividades.add(mnRegistrarVenta);

        jMenuBar1.add(mnActividades);

        mnStock.setText("Stock");

        mnVerificarStock.setText("Verificar Stock");
        mnStock.add(mnVerificarStock);

        jMenuBar1.add(mnStock);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegistrarCompraActionPerformed
        // TODO add your handling code here:
        panelRegistrarCompra.setVisible(true);
        panelRegistrarCompra.setSize(550,300);
        panelRegistrarCompra.setLocation(300,50);
        this.add(panelRegistrarCompra);
        revalidate();
        repaint();
        panelRegistrarVenta.setVisible(false);
        panelRegistrarCompra.llenarTabla();
       
        
        
    }//GEN-LAST:event_mnRegistrarCompraActionPerformed

    private void mnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegistrarVentaActionPerformed
        // TODO add your handling code here:
        panelRegistrarVenta.setVisible(true);
        panelRegistrarVenta.setSize(550,300);
        panelRegistrarVenta.setLocation(300,50);
        
        panelRegistrarCompra.setVisible(false);
        panelRegistrarVenta.llenarTabla();
        this.add(panelRegistrarVenta);
        revalidate();
        repaint();
        
        
        
    }//GEN-LAST:event_mnRegistrarVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEquiposInformaticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEquiposInformaticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEquiposInformaticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEquiposInformaticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEquiposInformaticos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnActividades;
    private javax.swing.JMenuItem mnRegistrarCompra;
    private javax.swing.JMenuItem mnRegistrarVenta;
    private javax.swing.JMenu mnStock;
    private javax.swing.JMenuItem mnVerificarStock;
    // End of variables declaration//GEN-END:variables
}
