/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.epn.VentanasProyectoFinal;


import ec.edu.epn.ClasesProyectoFinal.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author AnitaGabriela
 */
public class PnlVerificarStock extends javax.swing.JPanel {
    DefaultTableModel dtmModelo;
    /**
     * Creates new form PnlVerificarStock
     */
    public PnlVerificarStock() {
        initComponents();
        dtmModelo = new DefaultTableModel();
        dtmModelo.addColumn("Id");
        dtmModelo.addColumn("Nombre");
        dtmModelo.addColumn("Cantidad");
        dtmModelo.addColumn("Verificacion");
        tblDatos.setModel(dtmModelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnVerificarStock = new javax.swing.JButton();
        lblFondoVerificarStock = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        tblDatos.setBackground(new java.awt.Color(0, 51, 51));
        tblDatos.setForeground(new java.awt.Color(255, 255, 255));
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        btnVerificarStock.setBackground(new java.awt.Color(255, 255, 255));
        btnVerificarStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVerificarStock.setText("Verificar Stock");
        btnVerificarStock.setOpaque(false);
        btnVerificarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarStockActionPerformed(evt);
            }
        });

        lblFondoVerificarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/epn/VentanasProyectoFinal/FondoPnlRegistrarCompra.png"))); // NOI18N
        lblFondoVerificarStock.setMaximumSize(new java.awt.Dimension(838, 645));
        lblFondoVerificarStock.setPreferredSize(new java.awt.Dimension(838, 645));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btnVerificarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblFondoVerificarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(btnVerificarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblFondoVerificarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarStockActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i <= Listas.getProductos().size() - 1; i++) {
            if (Listas.getProductos().get(i).getStock() <= 0) {
                Listas.getProductos().get(i).setExistencias("No hay producto");
            } else {
                Listas.getProductos().get(i).setExistencias("Aun hay producto");
            }

            dtmModelo.setRowCount(0);
            for (Producto s : Listas.getProductos()) {
                dtmModelo.addRow(new Object[]{s.getId(), s.getNombre(),
                    s.getStock(), s.getExistencias()});
            }
        }
    }//GEN-LAST:event_btnVerificarStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificarStock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondoVerificarStock;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}