/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.epn.VentanasProyectoFinal;


import ec.edu.epn.ClasesProyectoFinal.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author AnitaGabriela
 */
public class PnlVerificarStock extends javax.swing.JPanel {

    DefaultTableModel dtmModelo;
   

    /**
     * Creates new form PnlVerificarStock
     */
    public PnlVerificarStock() {
        initComponents();
        dtmModelo = new DefaultTableModel();
        dtmModelo.addColumn("Id");
        dtmModelo.addColumn("Nombre");
        dtmModelo.addColumn("Cantidad");
        dtmModelo.addColumn("Verificacion");
        tblDatos.setModel(dtmModelo);
    }
    
    public void llenarTabla() {

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnVerificarStock = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaRespuesta = new javax.swing.JTextArea();

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        btnVerificarStock.setText("Verificar Stock");
        btnVerificarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarStockActionPerformed(evt);
            }
        });

        txaRespuesta.setColumns(20);
        txaRespuesta.setRows(5);
        jScrollPane2.setViewportView(txaRespuesta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btnVerificarStock)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnVerificarStock)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarStockActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i <= Listas.getProductos().size() - 1; i++) {
            if (Listas.getProductos().get(i).getStock() < 0) {
                Listas.getProductos().get(i).setExistencias("No hay producto");
            } else {
                Listas.getProductos().get(i).setExistencias("Aun hay producto");

            }
        }
        for (Producto s : Listas.getProductos()) {
            dtmModelo.addRow(new Object[]{s.getId(), s.getNombre(),
                s.getStock(), s.getExistencias()});

        }


    }//GEN-LAST:event_btnVerificarStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificarStock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextArea txaRespuesta;
    // End of variables declaration//GEN-END:variables
}